# WhatATheme
# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# URL of the Site
url: https://sparkerhoney.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Code highlighter
highlighter: rouge

# Title of the Site
title: Dive into Honey's Blog
# Description of the Site
description: Data Science & AI üíª
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/sparkerhoney/sparkerhoney.github.io/master/966A52E9-A9D0-4DCE-83DB-582D81F0D849_1_201_a.jpeg
# Keywords of the Site
site-keywords: Data Scientist, AI Developer, Prompt engineer
# URL for the Image of custom Favicon
favicon-url: https://raw.githubusercontent.com/sparkerhoney/sparkerhoney.github.io/master/favicon.png

darkmode_switch: true

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/sparkerhoney/sparkerhoney.github.io/blob/master/wallpaper_light.gif?raw=true
heroimage_dark: https://github.com/sparkerhoney/sparkerhoney.github.io/blob/master/wallpaper_dark.gif?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lhe339@gmail.com
facebook_username: 
twitter_username: 
instagram_username: ho.en.y
linkedin_username: 
github_username:  sparkerhoney
youtube_channel_id: 
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Honey
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/sparkerhoney/sparkerhoney.github.io/master/966A52E9-A9D0-4DCE-83DB-582D81F0D849_1_201_a.jpeg
# 60 Words About the Author
author-about: AI Researcherüë®üèª‚Äçüíª in Market Designers, MJU, Industrial Management Engineering, Data Science, AI, Deep learning, Seoul, South Korea
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/sparkerhoney

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/